name: Guardrails POC Action Test
description: Process security scan results through Guardrails API

inputs:
  scan_results_path:
    description: Path to the JSON file containing scan results
    required: true
  instruction_file_path:
    description: Path to the instruction file or directory containing instruction files
    required: true
  scanner_type:
    description: Type of scanner used (e.g., snyk, bandit)
    required: true
  api_url:
    description: Guardrails API URL
    required: true
  api_key:
    description: Guardrails API key
    required: true
  auto_commit:
    description: Automatically commit and push updated instruction file (default true)
    required: false
    default: 'true'

outputs:
  api_response:
    description: The response from the Guardrails API
  updated_instructions:
    description: The updated instructions content from the API response
  instruction_file:
    description: The resolved path to the instruction file that was processed

runs:
  using: node20
  main: dist/index.js